# netlify.toml

[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/prisma-plugin"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200